steps:
- name: 'docker/compose'
  args: ['up', '-d']
- name: "docker"
  args: ["push", "gcr.io/$PROJECT_ID/github.com/mozilla-it/$REPO_NAME:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  args:
  - '/workspace/infra/clouddeploy'
