steps:
- name: 'docker/compose:1.19.0'
  args: ['-f', './docker-compose.yaml', '-f', './tests/infra/docker-compose.test.yaml', 'build', '--build-arg', 'userid=10001', '--build-arg', 'groupid=10001', '-t', 'gcr.io/$PROJECT_ID/github.com/mozilla-it/$REPO_NAME:$SHORT_SHA']
- name: "docker"
  args: ["push", "gcr.io/$PROJECT_ID/github.com/mozilla-it/$REPO_NAME:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  args:
  - '/workspace/infra/clouddeploy'
